-- One row per customer. This replaces the previous design, where the customer's
-- name was interpolated into schema names, table names, function names and
-- column names, so onboarding required running DDL.
CREATE TABLE tenants (
    id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    slug       text NOT NULL UNIQUE,   -- 'chick_fil_a'; was the identifier infix
    name       text NOT NULL,          -- 'Chick-fil-A'
    kind       text NOT NULL CHECK (kind IN ('company', 'school')),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Who may read which tenant. Previously each tenant table carried its own
-- hand-written RLS policy naming that tenant, generated by a Python script;
-- a table whose policy was never generated was readable by any authenticated
-- user, and nothing detected that.
CREATE TABLE tenant_members (
    tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email     text   NOT NULL,
    is_admin  boolean NOT NULL DEFAULT false,
    PRIMARY KEY (tenant_id, email)
);

CREATE INDEX tenant_members_email_idx ON tenant_members (email);
